export const TODOLISTS_FETCH_START = "TODOLIST_FETCH_START";
export const TODOLISTS_FETCH_SUCCESS = "TODOLIST_FETCH_SUCCESS";
export const TODOLISTS_FETCH_ERROR = "TODOLIST_FETCH_ERROR";

export const TODOLIST_FETCH_START = "TODOLIST_FETCH_START";
export const TODOLIST_FETCH_SUCCESS = "TODOLIST_FETCH_SUCCESS";
export const TODOLIST_FETCH_FAIL = "TODOLIST_FETCH_FAIL";

export const DELETE_TODOLIST_START = "DELETE_TODOLIST_START";
export const DELETE_TODOLIST_SUCCESS = "DELETE_TODOLIST_SUCCESS";
export const DELETE_TODOLIST_FAIL = "DELETE_TODOLIST_FAIL";
export const DELETE_TODOLIST_RESET = "DELETE_TODOLIST_RESET";

export const CREATE_TODOLIST_START = "CREATE_TODOLIST_START";
export const CREATE_TODOLIST_SUCCESS = "CREATE_TODOLIST_SUCCESS";
export const CREATE_TODOLIST_FAIL = "CREATE_TODOLIST_FAIL";
export const CREATE_TODOLIST_RESET = "CREATE_TODOLIST_RESET";

export const EDIT_TODOLIST_START = "EDIT_TODOLIST_START";
export const EDIT_TODOLIST_SUCCESS = "EDIT_TODOLIST_SUCCESS";
export const EDIT_TODOLIST_FAIL = "EDIT_TODOLIST_FAIL";
export const EDIT_TODOLIST_RESET = "EDIT_TODOLIST_RESET";
